//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int AreaId { get; set; }
        public Nullable<int> TypeArea { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> NoSplit { get; set; }
        public Nullable<bool> AssemblyArea { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> MultipleOrders { get; set; }
        public Nullable<bool> HiddenArea { get; set; }
        public string IP { get; set; }
        public int PavilionId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> OrderExecution { get; set; }
        public Nullable<int> Dependence { get; set; }
        public Nullable<int> WorkingPeople { get; set; }
        public Nullable<int> ComponentTypeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> Segment { get; set; }
    }
}
