//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> DocumentCreateDate { get; set; }
        public Nullable<System.DateTime> DocumentCloseDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public Nullable<int> StockId { get; set; }
        public string MachinesSN { get; set; }
        public Nullable<decimal> HoursMachines { get; set; }
        public string Description { get; set; }
        public string SmcsCode { get; set; }
        public string ComponentSN { get; set; }
        public Nullable<System.DateTime> ComponentDismantlingDate { get; set; }
        public Nullable<decimal> PartsCost { get; set; }
        public Nullable<decimal> WorkCost { get; set; }
        public Nullable<decimal> ConsumablesCost { get; set; }
        public Nullable<bool> ApprovedServiceEngineer { get; set; }
        public Nullable<int> EngineModelId { get; set; }
        public Nullable<decimal> ComponentHours { get; set; }
        public Nullable<int> RepairTypeId { get; set; }
        public Nullable<System.DateTime> ArrivalMonth { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> DeliveryMethodId { get; set; }
        public Nullable<bool> ToPlan { get; set; }
        public Nullable<int> CabinetSE { get; set; }
        public Nullable<bool> IsArrived { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
