//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablesSNPrefix
    {
        public int intSNPrefixID { get; set; }
        public string strPrefix { get; set; }
        public Nullable<int> intModelID { get; set; }
    
        public virtual TablesModel TablesModel { get; set; }
    }
}
