//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerInactivity
    {
        public int TimerInactivityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<int> DurationInSeconds { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Comment { get; set; }
    }
}
