//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackEvaluationPart
    {
        public int intEvaluationPartId { get; set; }
        public Nullable<int> intEvalutionId { get; set; }
        public int intMasterPartId { get; set; }
        public Nullable<double> floatQuantity { get; set; }
        public Nullable<double> floatUnitCostTrack { get; set; }
        public Nullable<double> floatUnitCostAvia { get; set; }
        public string strAvailability { get; set; }
        public string strDescription { get; set; }
        public Nullable<int> intPartStatus { get; set; }
        public Nullable<int> intSimsId { get; set; }
    
        public virtual TrackEvaluation TrackEvaluation { get; set; }
    }
}
