//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackEvaluation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackEvaluation()
        {
            this.TrackEvaluationPart = new HashSet<TrackEvaluationPart>();
        }
    
        public int intEvalutionId { get; set; }
        public Nullable<int> intEvalutionNumber { get; set; }
        public Nullable<System.DateTime> dCreateDate { get; set; }
        public Nullable<int> intCreateUserId { get; set; }
        public Nullable<System.DateTime> dCreateDateBL { get; set; }
        public Nullable<int> intCreateUserIdBL { get; set; }
        public string CustomerRequestNumber { get; set; }
        public Nullable<int> intTypeOfInspection { get; set; }
        public Nullable<int> intSMCSComponentID { get; set; }
        public Nullable<int> intMachineSystem { get; set; }
        public Nullable<int> intStatysId { get; set; }
        public Nullable<System.DateTime> dSendDateCustomer { get; set; }
        public Nullable<System.DateTime> dReceiveDateCustomer { get; set; }
        public string strOrderNo { get; set; }
        public string strSalesOrderNumber { get; set; }
        public Nullable<System.DateTime> dDateOfSale { get; set; }
        public Nullable<System.DateTime> dEstimatedDateArrival { get; set; }
        public Nullable<System.DateTime> dArrivalDate { get; set; }
        public Nullable<int> intEquipmentID { get; set; }
        public Nullable<double> intMetered { get; set; }
        public string strDescriptionDefect { get; set; }
        public string strReasonDefect { get; set; }
        public string strRemedyDefect { get; set; }
        public string strSymptoms { get; set; }
        public Nullable<int> intPriority { get; set; }
        public Nullable<double> floatETTR { get; set; }
        public Nullable<double> floatELTR { get; set; }
        public Nullable<int> intConfirmUserId { get; set; }
        public Nullable<System.DateTime> dConfirmDate { get; set; }
        public Nullable<bool> intConfirmStatus { get; set; }
        public Nullable<int> intStatus { get; set; }
        public Nullable<int> intLocationId { get; set; }
        public Nullable<int> intServiceHistoryId { get; set; }
        public Nullable<int> intEvaluationSysStatusId { get; set; }
    
        public virtual newEquipment newEquipment { get; set; }
        public virtual TableEvaluationPriority TableEvaluationPriority { get; set; }
        public virtual TableEvaluationSysStatus TableEvaluationSysStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackEvaluationPart> TrackEvaluationPart { get; set; }
    }
}
